
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["MY_USERNAME"] %>
  password: <%= ENV["MY_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_e_sports_professional_curriculum_development

test:
  <<: *default
  database: rails_e_sports_professional_curriculum_test

production:
  <<: *default
  database: rails_e_sports_professional_curriculum_production
  username: rails_e_sports_professional_curriculum
  password: <%= ENV['RAILS_E_SPORTS_PROFESSIONAL_CURRICULUM_DATABASE_PASSWORD'] %>
